### ISSUE TITLE
Model wasn't fully converted on window11 with Ultra7 155H

### ISSUE THREAD

**Issue by mattchai** [OpenVINO-dev-contest/llama2.openvino#10]
(llama2) C:\Intel\llama2.openvino>python export.py --model_id meta-llama/Llama-2-7b-hf --output c:/models/Llama-2-7b-hf
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:50<00:00, 25.08s/it]
C:\env\llama2\llama2\lib\site-packages\transformers\modeling_utils.py:4225: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
The cos_cached attribute will be removed in 4.39. Bear in mind that its contents changed in v4.38. Use the forward method of RoPE from now on instead. It is not used in the `LlamaAttention` class
The sin_cached attribute will be removed in 4.39. Bear in mind that its contents changed in v4.38. Use the forward method of RoPE from now on instead. It is not used in the `LlamaAttention` class
C:\env\llama2\llama2\lib\site-packages\transformers\models\llama\modeling_llama.py:1075: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if sequence_length != 1:
C:\env\llama2\llama2\lib\site-packages\torch\jit\_trace.py:165: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  if a.grad is not None:
Traceback (most recent call last):
  File "C:\Intel\llama2.openvino\export.py", line 108, in <module>
    ov_model = ov.convert_model(pt_model, example_input=dummy_inputs)
  File "C:\env\llama2\llama2\lib\site-packages\openvino\tools\ovc\convert.py", line 100, in convert_model
    ov_model, _ = _convert(cli_parser, params, True)
  File "C:\env\llama2\llama2\lib\site-packages\openvino\tools\ovc\convert_impl.py", line 535, in _convert
    raise e
  File "C:\env\llama2\llama2\lib\site-packages\openvino\tools\ovc\convert_impl.py", line 477, in _convert
    ov_model = driver(argv, {"conversion_parameters": non_default_params})
  File "C:\env\llama2\llama2\lib\site-packages\openvino\tools\ovc\convert_impl.py", line 228, in driver
    ov_model = moc_emit_ir(prepare_ir(argv), argv)
  File "C:\env\llama2\llama2\lib\site-packages\openvino\tools\ovc\convert_impl.py", line 177, in prepare_ir
    ov_model = moc_pipeline(argv, moc_front_end)
  File "C:\env\llama2\llama2\lib\site-packages\openvino\tools\ovc\moc_frontend\pipeline.py", line 244, in moc_pipeline
    ov_model = moc_front_end.convert(input_model)
  File "C:\env\llama2\llama2\lib\site-packages\openvino\frontend\frontend.py", line 18, in convert
    converted_model = super().convert(model)
openvino._pyopenvino.OpConversionFailure: Check 'is_conversion_successful' failed at src\frontends\pytorch\src\frontend.cpp:143:
FrontEnd API failed with OpConversionFailure:
Model wasn't fully converted. Failed operations detailed log:
-- aten::mul with a message:
Exception happened during conversion of operation __module.model/aten::mul with schema aten::mul.Tensor(Tensor self, Tensor other) -> Tensor
Check 'args_et.is_dynamic() || args_et != element::boolean' failed at src\core\src\op\util\binary_elementwise_arithmetic.cpp:29:
While validating node 'opset1::Multiply Multiply_258 (opset1::Equal __module.model/aten::eq/Equal[0]:boolean[...], opset1::Equal __module.model/aten::eq/Equal[0]:boolean[?,1,1,?]) -> (dynamic[...])' with friendly_name 'Multiply_258':
Arguments cannot have boolean element type (argument element type: boolean).

Summary:
-- Conversion is failed for: aten::mul

**Comment by OpenVINO-dev-contest** [comment]
hi @mattchai what the version of openvino you are using ? Does this issue happen with "export_op.py" as well ?

**Comment by mattchai** [comment]
Hi, the openvino version I used is 2024.0.0.
export_op.py will happen another error as below, not sure if this command support windows11 OS or not.

ModuleNotFoundError: No module named 'scipy.stats._boost.nct_ufunc'


(llama2) C:\Intel\llama2.openvino>python export_op.py --model_id meta-llama/Llama-2-7b-hf --output c:/models/Llama-2-7b-hf
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Traceback (most recent call last):
  File "C:\env\llama2\llama2\lib\site-packages\transformers\utils\import_utils.py", line 1472, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\env\llama2\llama2\lib\site-packages\transformers\data\__init__.py", line 26, in <module>
    from .metrics import glue_compute_metrics, xnli_compute_metrics
  File "C:\env\llama2\llama2\lib\site-packages\transformers\data\metrics\__init__.py", line 19, in <module>
    from scipy.stats import pearsonr, spearmanr
  File "C:\env\llama2\llama2\lib\site-packages\scipy\stats\__init__.py", line 606, in <module>
    from ._stats_py import *
  File "C:\env\llama2\llama2\lib\site-packages\scipy\stats\_stats_py.py", line 49, in <module>
    from . import distributions
  File "C:\env\llama2\llama2\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "C:\env\llama2\llama2\lib\site-packages\scipy\stats\_continuous_distns.py", line 33, in <module>
    import scipy.stats._boost as _boost
  File "C:\env\llama2\llama2\lib\site-packages\scipy\stats\_boost\__init__.py", line 37, in <module>
    from scipy.stats._boost.nct_ufunc import (
ModuleNotFoundError: No module named 'scipy.stats._boost.nct_ufunc'

The above exception was the direct cause of the following exception:
