### ISSUE TITLE
Fail on NPU

### ISSUE THREAD

**Issue by Confuzzle** [OpenVINO-dev-contest/llama2.openvino#8]
I successfully ran some inferences on both CPU and GPU. 
However, the following error occured when I try to run inference on NPU.
```
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
 --- load tokenizer ---
 --- use local model ---
Compiling the model to NPU ...
Setting OpenVINO CACHE_DIR to ir_model\model_cache
Traceback (most recent call last):
  File "D:\llama2.openvino\pipeline\generate_op.py", line 40, in <module>
    model = OVModelForCausalLM.from_pretrained(args.model_id, device=args.device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PCM\AppData\Local\Programs\Python\Python311\Lib\site-packages\optimum\modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PCM\AppData\Local\Programs\Python\Python311\Lib\site-packages\optimum\intel\openvino\modeling_decoder.py", line 490, in _from_pretrained
    return init_cls(model=model, config=config, model_save_dir=model_cache_path.parent, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PCM\AppData\Local\Programs\Python\Python311\Lib\site-packages\optimum\intel\openvino\modeling_decoder.py", line 140, in __init__
    self.compile()
  File "C:\Users\PCM\AppData\Local\Programs\Python\Python311\Lib\site-packages\optimum\intel\openvino\modeling_decoder.py", line 287, in compile
    super().compile()
  File "C:\Users\PCM\AppData\Local\Programs\Python\Python311\Lib\site-packages\optimum\intel\openvino\modeling_base.py", line 348, in compile
    self.request = core.compile_model(self.model, self._device, ov_config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PCM\AppData\Local\Programs\Python\Python311\Lib\site-packages\openvino\runtime\ie_api.py", line 543, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Exception from src\inference\src\core.cpp:116:
[ GENERAL_ERROR ] Exception from src\vpux_plugin\src\plugin.cpp:579:
get_shape was called on a descriptor::Tensor with dynamic shape
```
What should I do?

**Comment by OpenVINO-dev-contest** [comment]
Hi @Confuzzle I believe NPU can not support llama2 yet.

**Comment by mattchai** [comment]
Hi @OpenVINO-dev-contest , do you know when NPU can support llama2?
